const wordList = [
    { word: "engine", hint: "The heart of a vehicle." },
    { word: "transmission", hint: "Changes gears for smooth driving." },
    { word: "brakes", hint: "Slows down or stops the vehicle." },
    { word: "radiator", hint: "Helps keep the engine cool." },
    { word: "suspension", hint: "Absorbs shocks and ensures a smooth ride." },
    { word: "exhaust", hint: "Releases gases from the engine." },
    { word: "battery", hint: "Provides electrical power to start the car." },
    { word: "tire", hint: "The rubber part that meets the road." },
    { word: "alternator", hint: "Generates electrical power for the car." },
    { word: "sparkplug", hint: "Ignites the fuel in the engine." },
    { word: "toolbox", hint: "Stores various tools for repairs." },
    { word: "lift", hint: "Raises the car for easy access underneath." },
    { word: "oildrum", hint: "Contains lubricant for the engine." },
    { word: "workbench", hint: "Provides a surface for repairs and assembly." },
    { word: "jackstand", hint: "Supports the car when lifted." },
    { word: "aircompressor", hint: "Inflates tires and powers pneumatic tools." },
    { word: "wrench", hint: "Used for tightening and loosening bolts." },
    { word: "oilfilter", hint: "Removes impurities from the engine oil." },
    { word: "greasegun", hint: "Applies lubricant to moving parts." },
    { word: "jumpercables", hint: "Used to start a car with a dead battery." },
];